import pandas as pd
import json
import os
from pathlib import Path

def generate_screening_report(csv_input="outputs/peptide_features.csv", output_html="outputs/screening_report.html"):
    if not os.path.exists(csv_input):
        print(f"⚠️ Cannot generate report: {csv_input} not found.")
        return

    df = pd.read_csv(csv_input)
    
    # Calculate some summary stats for the "Interpretability" section
    stats = {
        "total_screened": len(df),
        "cyclizable_count": int(df['Cyclizable'].sum()),
        "avg_charge": round(df['Net_Charge_pH7.4'].mean(), 2),
        "avg_gravy": round(df['Hydrophobicity_GRAVY'].mean(), 2)
    }

    # Convert data for Plotly (sampling 1000 points if dataset is huge for faster loading)
    plot_df = df.sample(min(1000, len(df)))

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Peptide-Guardian | Screening Report</title>
        <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; background-color: #f4f7f6; color: #333; }}
            .container {{ max-width: 1200px; margin: auto; background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
            .stats-grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; margin: 30px 0; }}
            .stat-card {{ background: #ecf0f1; padding: 20px; border-radius: 8px; text-align: center; border-left: 5px solid #3498db; }}
            .stat-value {{ font-size: 24px; font-weight: bold; color: #2980b9; }}
            .chart-container {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }}
            .chart {{ background: white; padding: 15px; border: 1px solid #ddd; border-radius: 8px; }}
            footer {{ margin-top: 50px; font-size: 0.9em; color: #7f8c8d; text-align: center; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🛡️ Peptide-Guardian Screening Dashboard</h1>
            <p>ADMET & Cyclization Metrics for 15,000 Sequences</p>
            
            <div class="stats-grid">
                <div class="stat-card"><div class="stat-label">Total Screened</div><div class="stat-value">{stats['total_screened']}</div></div>
                <div class="stat-card"><div class="stat-label">Cyclizable (Cys&ge;2)</div><div class="stat-value">{stats['cyclizable_count']}</div></div>
                <div class="stat-card"><div class="stat-label">Avg. Net Charge</div><div class="stat-value">{stats['avg_charge']}</div></div>
                <div class="stat-card"><div class="stat-label">Avg. Hydrophobicity</div><div class="stat-value">{stats['avg_gravy']}</div></div>
            </div>

            <div class="chart-container">
                <div id="charge-gravy-scatter" class="chart"></div>
                <div id="cyclization-pie" class="chart"></div>
                <div id="mw-dist" class="chart" style="grid-column: span 2;"></div>
            </div>

            <footer>
                Generated by Silva Architecture | Peptide-Guardian Sprint 2026
            </footer>
        </div>

        <script>
            // 1. Charge vs Hydrophobicity Scatter
            const trace1 = {{
                x: {plot_df['Net_Charge_pH7.4'].tolist()},
                y: {plot_df['Hydrophobicity_GRAVY'].tolist()},
                mode: 'markers',
                type: 'scatter',
                name: 'Peptides',
                marker: {{ color: '#3498db', opacity: 0.6 }}
            }};
            Plotly.newPlot('charge-gravy-scatter', [trace1], {{ title: 'ADMET Landscape: Charge vs Hydrophobicity' }});

            // 2. Cyclization Potential Pie Chart
            const trace2 = {{
                values: [{stats['cyclizable_count']}, {stats['total_screened'] - stats['cyclizable_count']}],
                labels: ['Cyclizable', 'Linear'],
                type: 'pie',
                marker: {{ colors: ['#27ae60', '#bdc3c7'] }}
            }};
            Plotly.newPlot('cyclization-pie', [trace2], {{ title: 'Developability: Cyclization Potential' }});

            // 3. Molecular Weight Distribution
            const trace3 = {{
                x: {df['MW'].tolist()},
                type: 'histogram',
                marker: {{ color: '#e67e22' }}
            }};
            Plotly.newPlot('mw-dist', [trace3], {{ title: 'Molecular Weight (Da) Distribution' }});
        </script>
    </body>
    </html>
    """
    
    with open(output_html, "w") as f:
        f.write(html_content)
    print(f"✅ Dashboard generated at {output_html}")

if __name__ == "__main__":
    generate_screening_report()