import json
import os

def generate_model_report(metrics, output_html="results/classification_report.html"):
    # Ensure results directory exists
    os.makedirs("results", exist_ok=True)
    
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Peptide-Guardian | Intelligence Report</title>
        <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
        <style>
            body {{ font-family: sans-serif; margin: 40px; background: #f4f7f6; color: #333; }}
            .container {{ max-width: 1100px; margin: auto; background: white; padding: 30px; border-radius: 15px; box-shadow: 0 4px 20px rgba(0,0,0,0.08); }}
            h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
            .metric-grid {{ display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; margin: 30px 0; }}
            .card {{ background: #2c3e50; color: white; padding: 25px; border-radius: 10px; text-align: center; }}
            .card h2 {{ font-size: 36px; margin: 10px 0; color: #3498db; }}
            .chart-container {{ display: grid; grid-template-columns: 1fr; gap: 30px; }}
            .chart {{ background: white; padding: 20px; border: 1px solid #eee; border-radius: 10px; }}
            .bias-note {{ background: #fff3cd; color: #856404; padding: 15px; border-radius: 5px; border: 1px solid #ffeeba; margin-top: 20px; font-size: 0.9em; }}
            footer {{ margin-top: 50px; text-align: center; color: #7f8c8d; font-size: 0.8em; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Peptide-Guardian Intelligence Dashboard</h1>
            <p>Evaluating the Ensemble Classification Engine on training sequences.</p>

            <div class="metric-grid">
                <div class="card">
                    <span>Validation Accuracy</span>
                    <h2>{metrics['accuracy']:.2%}</h2>
                </div>
                <div class="card">
                    <span>Model Robustness (AUC)</span>
                    <h2>{metrics['auc']:.4f}</h2>
                </div>
            </div>

            <div class="chart-container">
                <div id="feature-importance" class="chart"></div>
                <div id="prediction-confidence" class="chart"></div>
            </div>

            <div class="bias-note">
                <strong>Anti-Bias Verification:</strong> Model trained on deduplicated sequences with depth-limited trees to ensure biophysical rule learning.
            </div>

            <footer>
                Generated by Silva Architecture | 2026
            </footer>
        </div>

        <script>
            const importanceData = [{{
                x: {metrics['feature_names']},
                y: {metrics['feature_importance']},
                type: 'bar',
                marker: {{ color: '#3498db' }}
            }}];

            Plotly.newPlot('feature-importance', importanceData, {{
                title: 'Scientific Drivers',
                yaxis: {{ title: 'Importance Score' }},
                xaxis: {{ title: 'Feature' }}
            }});

            const classData = [{{
                values: {metrics['class_counts']},
                labels: {metrics['class_names']},
                type: 'pie',
                hole: 0.4,
                marker: {{ colors: ['#3498db', '#e74c3c', '#f1c40f', '#bdc3c7'] }}
            }}];

            Plotly.newPlot('prediction-confidence', classData, {{
                title: 'Training Set Balance'
            }});
        </script>
    </body>
    </html>
    """
    
    with open(output_html, "w") as f:
        f.write(html_content)
    
    print(f"Model performance report generated: {output_html}")