[workflow]
name = "silva-test"

[workspace]
nodes = ["a_ingest", "b_features", "c_model", "d_prediction"]

[dependencies]
"b_features" = ["a_ingest"]
"c_model" = ["b_features"]
"d_prediction" = ["c_model"]